-- Test groups mirror the repository contracts.

return {
  public = {
    'tests/public/test_contracts.lua',
    'examples/test_documented_examples.lua',
    'tests/public/test_flow.lua',
    'tests/public/test_op.lua',
    'tests/public/test_closure.lua',
    'tests/public/test_performing_conveniences.lua',
    'tests/public/test_public_surface.lua',
    'tests/public/test_sleep.lua',
    'tests/public/test_stream_memory.lua',
  },
  composition = {
    'examples/recipes/tests/test_messaging_and_countdown.lua',
    'examples/recipes/tests/test_priority_queue_composition.lua',
    'examples/recipes/tests/test_resources_and_pool.lua',
    'examples/recipes/tests/test_scalar_and_rate_limiter.lua',
  },
  resources = {
    'tests/resources/test_counter_and_fifo.lua',
    'tests/resources/test_external_resources.lua',
    'tests/resources/test_index.lua',
    'tests/resources/test_index_lease_extended.lua',
    'tests/resources/test_lease_laws.lua',
    'tests/resources/test_event.lua',
    'tests/resources/test_scalar.lua',
    'tests/resources/test_state_resource_laws.lua',
    'tests/resources/test_standard_compounds.lua',
  },
  lifetimes = {
    'tests/lifetimes/test_concurrent_task_closure.lua',
    'tests/lifetimes/test_effects.lua',
    'tests/lifetimes/test_mixed_claim_exchange.lua',
    'tests/lifetimes/test_lifetime_store.lua',
    'tests/lifetimes/test_lifetime_closure.lua',
    'tests/lifetimes/test_lifetime_views.lua',
    'tests/lifetimes/test_scope.lua',
    'tests/lifetimes/test_scope_grants.lua',
    'tests/lifetimes/test_scope_hardening.lua',
    'tests/lifetimes/test_scope_laws.lua',
    'tests/lifetimes/test_scope_closure_mechanisms.lua',
    'tests/lifetimes/test_scope_result_run.lua',
    'tests/lifetimes/test_scope_structural.lua',
    'tests/lifetimes/test_structured_closure.lua',
  },
  io = {
    'tests/io/test_datagram.lua',
    'tests/io/test_datagram_conformance.lua',
    'tests/io/test_dns_resolver.lua',
    'tests/io/test_happy_eyeballs.lua',
    'tests/io/test_foundations.lua',
    'tests/io/test_file.lua',
    'tests/io/test_pipe.lua',
    'tests/io/test_process.lua',
    'tests/io/test_socket.lua',
    'tests/io/test_socket_hardening.lua',
    'tests/io/test_socket_failure_matrix.lua',
    'tests/io/test_socket_lifecycle.lua',
    'tests/io/test_socket_provider_matrix.lua',
    'tests/io/test_socket_conformance.lua',
    'tests/io/test_resolver.lua',
  },
  embedding = {
    'tests/embedding/test_host.lua',
    'tests/embedding/test_roblox.lua',
    'tests/embedding/test_host_handle.lua',
    'tests/embedding/test_host_offer.lua',
    'tests/embedding/test_fd_nixio_wrap.lua',
    'tests/embedding/test_process_nixio_provider.lua',
    'tests/embedding/test_socket_resolver_optional_providers.lua',
    'tests/embedding/test_datagram_optional_providers.lua',
    'tests/embedding/test_host_linux.lua',
    'tests/embedding/test_host_poller.lua',
    'tests/embedding/test_readiness.lua',
    'tests/embedding/test_runtime.lua',
    'tests/embedding/test_runtime_lifecycle.lua',
    'tests/embedding/test_stream_reactor.lua',
    'tests/embedding/test_stream_host_handle.lua',
  },
  native = {
    'tests/embedding/hosts/test_pure.lua',
    'tests/embedding/hosts/test_nixio.lua',
    'tests/embedding/hosts/test_luaposix.lua',
    'tests/embedding/hosts/test_luajit_linux.lua',
    'tests/embedding/hosts/test_fd_luajit.lua',
    'tests/embedding/hosts/test_cffi_linux.lua',
    'tests/embedding/hosts/test_fd_cffi.lua',
    'tests/embedding/hosts/test_fd_luaposix.lua',
    'tests/embedding/hosts/test_fd_nixio.lua',
    'tests/native/test_datagram_native.lua',
    'tests/native/test_process_native.lua',
  },
  stress = {
    'tests/stress/test_stream_reactor_stress.lua',
    'tests/stress/test_socket_churn.lua',
    'tests/stress/test_datagram_churn.lua',
  },
  kernel = {
    'tests/kernel/test_claim_closure.lua',
    'tests/kernel/test_dependency_supply_direction.lua',
    'tests/kernel/test_exchange_choice_propagation.lua',
    'tests/kernel/test_defeat.lua',
    'tests/kernel/test_guard_activations.lua',
    'tests/kernel/test_instrumentation.lua',
    'tests/kernel/test_invariants.lua',
    'tests/kernel/test_kernel_machine.lua',
    'tests/kernel/test_ledger_kernel.lua',
    'tests/kernel/test_minimal_lazy_path.lua',
    'tests/kernel/test_residual_or_else.lua',
    'tests/kernel/test_resumable_search.lua',
    'tests/kernel/test_retry_laws.lua',
    'tests/kernel/test_retry_semantics.lua',
    'tests/kernel/test_search_stack.lua',
    'tests/kernel/test_search_limits.lua',
    'tests/kernel/test_slim_retention.lua',
    'tests/kernel/test_store_algebra.lua',
    'tests/kernel/test_store_rollback.lua',
    'tests/kernel/test_trail_journal.lua',
    'tests/kernel/test_validation_paths.lua',
    'tests/kernel/test_witness_validation.lua',
  },
  internal = {
    'tests/internal/test_host_hold.lua',
    'tests/internal/test_closed_op_conformance.lua',
    'tests/internal/test_io_audit.lua',
    'tests/internal/test_bitops.lua',
    'tests/internal/test_dns_codec.lua',
    'tests/internal/test_dns_hardening.lua',
    'tests/internal/test_algebraic_dns_reference.lua',
    'tests/internal/test_flow_helpers.lua',
    'tests/internal/test_flow_storage.lua',
    'tests/internal/test_flow_scalar_state_machine.lua',
    'tests/internal/test_flow_closure.lua',
    'tests/internal/test_flow_stream_adversarial.lua',
    'tests/internal/test_flow_validation.lua',
    'tests/internal/test_protected.lua',
    'tests/internal/test_reference_lazy.lua',
  },
  case_studies = {
    'examples/case_studies/calendar/test_calendar.lua',
    'examples/case_studies/calendar/test_calendar_completeness.lua',
    'examples/case_studies/petri/test_petri.lua',
  },
  performance = {
    'tests/performance/test_performance_architecture.lua',
  },
}
