-- Test groups mirror the repository contracts.

return {
  public = {
    'tests/public/test_contracts.lua',
    'tests/public/test_documented_examples.lua',
    'tests/public/test_flow.lua',
    'tests/public/test_op.lua',
    'tests/public/test_policy.lua',
    'tests/public/test_public_surface.lua',
    'tests/public/test_sleep.lua',
    'tests/public/test_stream_memory.lua',
  },
  composition = {
    'tests/composition/test_messaging_and_countdown.lua',
    'tests/composition/test_priority_queue_composition.lua',
    'tests/composition/test_resources_and_pool.lua',
    'tests/composition/test_scalar_and_rate_limiter.lua',
  },
  resources = {
    'tests/resources/test_counter_and_fifo.lua',
    'tests/resources/test_external_resources.lua',
    'tests/resources/test_index.lua',
    'tests/resources/test_index_lease_extended.lua',
    'tests/resources/test_lease_laws.lua',
    'tests/resources/test_resources.lua',
    'tests/resources/test_state_resource_laws.lua',
  },
  lifetimes = {
    'tests/lifetimes/test_concurrent_task_settlement.lua',
    'tests/lifetimes/test_effects.lua',
    'tests/lifetimes/test_mixed_claim_exchange.lua',
    'tests/lifetimes/test_region_general.lua',
    'tests/lifetimes/test_region_laws.lua',
    'tests/lifetimes/test_region_lifecycle.lua',
    'tests/lifetimes/test_region_task_effects.lua',
    'tests/lifetimes/test_scope.lua',
    'tests/lifetimes/test_scope_authority_borrow.lua',
    'tests/lifetimes/test_scope_hardening.lua',
    'tests/lifetimes/test_scope_laws.lua',
    'tests/lifetimes/test_scope_policy_mechanisms.lua',
    'tests/lifetimes/test_scope_result_run.lua',
    'tests/lifetimes/test_scope_structural.lua',
    'tests/lifetimes/test_settlement_structure.lua',
    'tests/lifetimes/test_structured_policy.lua',
  },
  embedding = {
    'tests/embedding/hosts/test_all.lua',
    'tests/embedding/test_host.lua',
    'tests/embedding/test_host_handle.lua',
    'tests/embedding/test_host_linux.lua',
    'tests/embedding/test_host_poller.lua',
    'tests/embedding/test_readiness.lua',
    'tests/embedding/test_runtime.lua',
    'tests/embedding/test_runtime_lifecycle.lua',
    'tests/embedding/test_stream_reactor.lua',
    'tests/embedding/test_stream_socket_backend.lua',
  },
  kernel = {
    'tests/kernel/test_defeat.lua',
    'tests/kernel/test_guard_activations.lua',
    'tests/kernel/test_instrumentation.lua',
    'tests/kernel/test_invariants.lua',
    'tests/kernel/test_kernel_machine.lua',
    'tests/kernel/test_minimal_lazy_path.lua',
    'tests/kernel/test_residual_or_else.lua',
    'tests/kernel/test_resumable_search.lua',
    'tests/kernel/test_retry_laws.lua',
    'tests/kernel/test_retry_semantics.lua',
    'tests/kernel/test_search_session_reopen.lua',
    'tests/kernel/test_search_stack.lua',
    'tests/kernel/test_search_state_identity.lua',
    'tests/kernel/test_slim_retention.lua',
    'tests/kernel/test_store_algebra.lua',
    'tests/kernel/test_store_rollback.lua',
    'tests/kernel/test_validation_paths.lua',
    'tests/kernel/test_witness_validation.lua',
  },
  internal = {
    'tests/internal/test_bitops.lua',
    'tests/internal/test_flow_helpers.lua',
    'tests/internal/test_flow_reservoir.lua',
    'tests/internal/test_flow_scalar_state_machine.lua',
    'tests/internal/test_flow_settlement.lua',
    'tests/internal/test_flow_stream_adversarial.lua',
    'tests/internal/test_flow_validation.lua',
    'tests/internal/test_protected.lua',
    'tests/internal/test_reference_lazy.lua',
  },
  case_studies = {
    'tests/case_studies/test_calendar.lua',
    'tests/case_studies/test_calendar_completeness.lua',
    'tests/case_studies/test_petri.lua',
  },
  experiments = {
    'tests/experiments/test_phase.lua',
  },
  performance = {
    'tests/performance/test_performance_architecture.lua',
  },
}
