-- Luau build profiles and test capabilities.
return {
  entries = {
    'fibers',
    'fibers.channel',
    'fibers.diagnostics.io',
    'fibers.diagnostics.search',
    'fibers.effect',
    'fibers.io.auto',
    'fibers.embed.application',
    'fibers.embed.queue',
    'fibers.embed.external',
    'fibers.embed.manual',
    'fibers.embed.pure',
    'fibers.roblox.host',
    'fibers.io.readiness',
    'fibers.latch',
    'fibers.mailbox',
    'fibers.resource.ref_count',
    'fibers.semaphore',
    'fibers.roblox',
    'fibers.roblox.subscription',
    'fibers.op',
    'fibers.perform',
    'fibers.closure',
    'fibers.grant',
    'fibers.pulse',
    'fibers.lifetime',
    'fibers.io.internal.acquired',
    'fibers.internal.lifetime.closure',
    'fibers.lifetime.store',
    'fibers.resource.authoring',
    'fibers.resource.clock',
    'fibers.resource.completion',
    'fibers.resource.counter',
    'fibers.resource.event_queue',
    'fibers.resource.flow',
    'fibers.resource.flow.errors',
    'fibers.resource.flow.rope',
    'fibers.resource.index',
    'fibers.resource.keyed',
    'fibers.resource.lease',
    'fibers.resource.machine',
    'fibers.resource.fifo',
    'fibers.resource.rendezvous',
    'fibers.resource.cell',
    'fibers.resource.signal',
    'fibers.runtime',
    'fibers.scope',
    'fibers.sleep',
    'fibers.stream',
    'fibers.task',
  },
  profiles = {
    portable = {
      tests = {
        'tests/public/test_contracts.lua',
        'examples/test_documented_examples.lua',
        'tests/public/test_flow.lua',
        'tests/public/test_op.lua',
        'tests/public/test_labels_and_execution.lua',
        'tests/public/test_closure.lua',
        'tests/public/test_performing_conveniences.lua',
        'tests/public/test_public_surface.lua',
        'tests/public/test_sleep.lua',
        'tests/public/test_stream_memory.lua',
        'examples/recipes/tests/test_messaging_and_countdown.lua',
        'examples/recipes/tests/test_priority_queue_composition.lua',
        'examples/recipes/tests/test_resources_and_pool.lua',
        'examples/recipes/tests/test_cell_and_rate_limiter.lua',
        'tests/resources/test_counter_and_fifo.lua',
        'tests/resources/test_event.lua',
        'tests/resources/test_external_resources.lua',
        'tests/resources/test_index.lua',
        'tests/resources/test_index_lease_extended.lua',
        'tests/resources/test_lease_laws.lua',
        'tests/resources/test_cell.lua',
        'tests/resources/test_machine_managed_values.lua',
        'tests/resources/test_state_resource_laws.lua',
        'tests/resources/test_standard_compounds.lua',
        'tests/lifetimes/test_concurrent_task_closure.lua',
        'tests/lifetimes/test_effects.lua',
        'tests/lifetimes/test_mixed_claim_exchange.lua',
        'tests/lifetimes/test_phase_integrity.lua',
        'tests/lifetimes/test_lifetime_store.lua',
        'tests/lifetimes/test_lifetime_closure.lua',
        'tests/lifetimes/test_lifetime_views.lua',
        'tests/lifetimes/test_scope.lua',
        'tests/lifetimes/test_scope_grants.lua',
        'tests/lifetimes/test_scope_hardening.lua',
        'tests/lifetimes/test_scope_laws.lua',
        'tests/lifetimes/test_scope_closure_mechanisms.lua',
        'tests/lifetimes/test_scope_result_run.lua',
        'tests/lifetimes/test_scope_structural.lua',
        'tests/lifetimes/test_structured_closure.lua',
        'tests/embedding/test_host.lua',
        'tests/embedding/test_embed.lua',
        'tests/embedding/test_platform.lua',
        'tests/embedding/test_roblox.lua',
        'tests/embedding/test_host_handle.lua',
        'tests/embedding/test_host_offer.lua',
        'tests/embedding/test_readiness.lua',
        'tests/embedding/test_runtime.lua',
        'tests/embedding/test_runtime_lifecycle.lua',
        'tests/embedding/test_stream_host_handle.lua',
        'tests/embedding/test_stream_reactor.lua',
        'tests/kernel/test_claim_closure.lua',
        'tests/kernel/test_compact_authoring.lua',
        'tests/kernel/test_defeat.lua',
        'tests/kernel/test_deterministic_transcript.lua',
        'tests/kernel/test_dependency_supply_direction.lua',
        'tests/kernel/test_demand_frontier_matching.lua',
        'tests/kernel/test_exchange_choice_propagation.lua',
        'tests/kernel/test_proof_index.lua',
        'tests/kernel/test_guard_activations.lua',
        'tests/kernel/test_instrumentation.lua',
        'tests/kernel/test_invariants.lua',
        'tests/kernel/test_join_and_active_order_regressions.lua',
        'tests/kernel/test_minimal_lazy_path.lua',
        'tests/kernel/test_residual_or_else.lua',
        'tests/kernel/test_resumable_search.lua',
        'tests/kernel/test_retry_laws.lua',
        'tests/kernel/test_retry_semantics.lua',
        'tests/kernel/test_search_limits.lua',
        'tests/kernel/test_search_stack.lua',
        'tests/kernel/test_slim_retention.lua',
        'tests/kernel/test_kernel.lua',
        'tests/kernel/test_store_algebra.lua',
        'tests/kernel/test_store_rollback.lua',
        'tests/kernel/test_trail_journal.lua',
        'tests/kernel/test_validation_paths.lua',
        'tests/kernel/test_cursor_validation.lua',
        'tests/internal/test_acquired.lua',
        'tests/internal/test_managed_value.lua',
        'tests/internal/test_closed_op_conformance.lua',
        'tests/internal/test_flow_helpers.lua',
        'tests/internal/test_flow_cell_state_machine.lua',
        'tests/internal/test_flow_closure.lua',
        'tests/internal/test_flow_storage.lua',
        'tests/internal/test_flow_stream_adversarial.lua',
        'tests/internal/test_flow_validation.lua',
        'tests/internal/test_io_audit.lua',
        'tests/internal/test_protected.lua',
        'examples/case_studies/calendar/test_calendar.lua',
        'examples/case_studies/calendar/test_calendar_completeness.lua',
        'examples/case_studies/petri/test_petri.lua',
      },
    },
  },
  classifications = {
    ['examples/case_studies/calendar/test_calendar.lua'] = 'portable',
    ['examples/case_studies/calendar/test_calendar_completeness.lua'] = 'portable',
    ['examples/case_studies/petri/test_petri.lua'] = 'portable',
    ['examples/recipes/tests/test_messaging_and_countdown.lua'] = 'portable',
    ['examples/recipes/tests/test_priority_queue_composition.lua'] = 'portable',
    ['examples/recipes/tests/test_resources_and_pool.lua'] = 'portable',
    ['examples/recipes/tests/test_cell_and_rate_limiter.lua'] = 'portable',
    ['tests/embedding/hosts/test_cffi_linux.lua'] = 'host_specific',
    ['tests/embedding/hosts/test_fd_cffi.lua'] = 'host_specific',
    ['tests/embedding/hosts/test_fd_luajit.lua'] = 'host_specific',
    ['tests/embedding/hosts/test_fd_luaposix.lua'] = 'host_specific',
    ['tests/embedding/hosts/test_fd_nixio.lua'] = 'host_specific',
    ['tests/embedding/hosts/test_luajit_linux.lua'] = 'host_specific',
    ['tests/embedding/hosts/test_luaposix.lua'] = 'host_specific',
    ['tests/embedding/hosts/test_nixio.lua'] = 'host_specific',
    ['tests/embedding/hosts/test_pure.lua'] = 'host_specific',
    ['tests/embedding/test_datagram_optional_providers.lua'] = 'host_specific',
    ['tests/embedding/test_fd_nixio_wrap.lua'] = 'host_specific',
    ['tests/embedding/test_host.lua'] = 'portable',
    ['tests/embedding/test_embed.lua'] = 'portable',
    ['tests/embedding/test_platform.lua'] = 'portable',
    ['tests/embedding/test_roblox.lua'] = 'portable',
    ['tests/embedding/test_host_handle.lua'] = 'portable',
    ['tests/embedding/test_host_offer.lua'] = 'portable',
    ['tests/embedding/test_host_linux.lua'] = 'host_specific',
    ['tests/embedding/test_host_poller.lua'] = 'host_specific',
    ['tests/embedding/test_process_nixio_provider.lua'] = 'host_specific',
    ['tests/embedding/test_readiness.lua'] = 'portable',
    ['tests/embedding/test_runtime.lua'] = 'portable',
    ['tests/embedding/test_runtime_lifecycle.lua'] = 'portable',
    ['tests/embedding/test_socket_resolver_optional_providers.lua'] = 'host_specific',
    ['tests/embedding/test_stream_host_handle.lua'] = 'portable',
    ['tests/embedding/test_stream_reactor.lua'] = 'portable',
    ['tests/internal/test_context.lua'] = 'stock_lua_loader',
    ['tests/internal/test_acquired.lua'] = 'portable',
    ['tests/internal/test_managed_value.lua'] = 'portable',
    ['tests/internal/test_native_file_sync.lua'] = 'host_specific',
    ['tests/internal/test_package_structure.lua'] = 'host_specific',
    ['tests/internal/test_closed_op_conformance.lua'] = 'portable',
    ['tests/internal/test_bitops.lua'] = 'stock_lua_loader',
    ['tests/internal/test_algebraic_dns_reference.lua'] = 'host_specific',
    ['tests/internal/test_dns_codec.lua'] = 'stock_lua_loader',
    ['tests/internal/test_dns_hardening.lua'] = 'stock_lua_loader',
    ['tests/internal/test_flow_helpers.lua'] = 'portable',
    ['tests/internal/test_flow_cell_state_machine.lua'] = 'portable',
    ['tests/internal/test_flow_closure.lua'] = 'portable',
    ['tests/internal/test_flow_storage.lua'] = 'portable',
    ['tests/internal/test_flow_stream_adversarial.lua'] = 'portable',
    ['tests/internal/test_flow_validation.lua'] = 'portable',
    ['tests/internal/test_io_audit.lua'] = 'portable',
    ['tests/internal/test_protected.lua'] = 'portable',
    ['tests/io/test_datagram.lua'] = 'host_specific',
    ['tests/io/test_datagram_conformance.lua'] = 'host_specific',
    ['tests/io/test_dns_resolver.lua'] = 'host_specific',
    ['tests/io/test_happy_eyeballs.lua'] = 'host_specific',
    ['tests/io/test_file.lua'] = 'host_specific',
    ['tests/io/test_foundations.lua'] = 'host_specific',
    ['tests/io/test_pipe.lua'] = 'host_specific',
    ['tests/io/test_process.lua'] = 'host_specific',
    ['tests/io/test_resolver.lua'] = 'host_specific',
    ['tests/io/test_socket.lua'] = 'host_specific',
    ['tests/io/test_socket_conformance.lua'] = 'host_specific',
    ['tests/io/test_socket_failure_matrix.lua'] = 'host_specific',
    ['tests/io/test_socket_hardening.lua'] = 'host_specific',
    ['tests/io/test_socket_lifecycle.lua'] = 'host_specific',
    ['tests/io/test_socket_provider_matrix.lua'] = 'host_specific',
    ['tests/kernel/test_claim_closure.lua'] = 'portable',
    ['tests/kernel/test_compact_authoring.lua'] = 'portable',
    ['tests/kernel/test_defeat.lua'] = 'portable',
    ['tests/kernel/test_deterministic_transcript.lua'] = 'portable',
    ['tests/kernel/test_dependency_supply_direction.lua'] = 'portable',
    ['tests/kernel/test_demand_frontier_matching.lua'] = 'portable',
    ['tests/kernel/test_exchange_choice_propagation.lua'] = 'portable',
    ['tests/kernel/test_proof_index.lua'] = 'portable',
    ['tests/kernel/test_guard_activations.lua'] = 'portable',
    ['tests/kernel/test_instrumentation.lua'] = 'portable',
    ['tests/kernel/test_invariants.lua'] = 'portable',
    ['tests/kernel/test_join_and_active_order_regressions.lua'] = 'portable',
    ['tests/kernel/test_minimal_lazy_path.lua'] = 'portable',
    ['tests/kernel/test_residual_or_else.lua'] = 'portable',
    ['tests/kernel/test_resumable_search.lua'] = 'portable',
    ['tests/kernel/test_retry_laws.lua'] = 'portable',
    ['tests/kernel/test_retry_semantics.lua'] = 'portable',
    ['tests/kernel/test_search_limits.lua'] = 'portable',
    ['tests/kernel/test_search_stack.lua'] = 'portable',
    ['tests/kernel/test_slim_retention.lua'] = 'portable',
    ['tests/kernel/test_kernel.lua'] = 'portable',
    ['tests/kernel/test_store_algebra.lua'] = 'portable',
    ['tests/kernel/test_store_rollback.lua'] = 'portable',
    ['tests/kernel/test_trail_journal.lua'] = 'portable',
    ['tests/kernel/test_validation_paths.lua'] = 'portable',
    ['tests/kernel/test_cursor_validation.lua'] = 'portable',
    ['tests/lifetimes/test_concurrent_task_closure.lua'] = 'portable',
    ['tests/lifetimes/test_effects.lua'] = 'portable',
    ['tests/lifetimes/test_mixed_claim_exchange.lua'] = 'portable',
    ['tests/lifetimes/test_phase_integrity.lua'] = 'portable',
    ['tests/lifetimes/test_lifetime_store.lua'] = 'portable',
    ['tests/lifetimes/test_lifetime_closure.lua'] = 'portable',
    ['tests/lifetimes/test_lifetime_views.lua'] = 'portable',
    ['tests/lifetimes/test_scope.lua'] = 'portable',
    ['tests/lifetimes/test_scope_grants.lua'] = 'portable',
    ['tests/lifetimes/test_scope_hardening.lua'] = 'portable',
    ['tests/lifetimes/test_scope_laws.lua'] = 'portable',
    ['tests/lifetimes/test_scope_closure_mechanisms.lua'] = 'portable',
    ['tests/lifetimes/test_scope_result_run.lua'] = 'portable',
    ['tests/lifetimes/test_scope_structural.lua'] = 'portable',
    ['tests/lifetimes/test_structured_closure.lua'] = 'portable',
    ['tests/native/test_datagram_native.lua'] = 'host_specific',
    ['tests/native/test_process_native.lua'] = 'host_specific',
    ['tests/reference/test_evaluator.lua'] = 'stock_lua_loader',
    ['tests/reference/test_frontier_conformance.lua'] = 'stock_lua_loader',
    ['tests/reference/test_facility_authoring_conformance.lua'] = 'portable',
    ['tests/public/test_contracts.lua'] = 'portable',
    ['examples/test_documented_examples.lua'] = 'portable',
    ['tests/public/test_flow.lua'] = 'portable',
    ['tests/public/test_op.lua'] = 'portable',
    ['tests/public/test_labels_and_execution.lua'] = 'portable',
    ['tests/public/test_performing_conveniences.lua'] = 'portable',
    ['tests/public/test_closure.lua'] = 'portable',
    ['tests/public/test_public_surface.lua'] = 'portable',
    ['tests/public/test_sleep.lua'] = 'portable',
    ['tests/public/test_stream_memory.lua'] = 'portable',
    ['tests/public/test_strict_v1.lua'] = 'portable',
    ['tests/resources/test_counter_and_fifo.lua'] = 'portable',
    ['tests/resources/test_event.lua'] = 'portable',
    ['tests/resources/test_external_resources.lua'] = 'portable',
    ['tests/resources/test_index.lua'] = 'portable',
    ['tests/resources/test_index_lease_extended.lua'] = 'portable',
    ['tests/resources/test_lease_laws.lua'] = 'portable',
    ['tests/resources/test_cell.lua'] = 'portable',
    ['tests/resources/test_machine_managed_values.lua'] = 'portable',
    ['tests/resources/test_state_resource_laws.lua'] = 'portable',
    ['tests/resources/test_standard_compounds.lua'] = 'portable',
    ['tests/stress/test_datagram_churn.lua'] = 'host_specific',
    ['tests/stress/test_socket_churn.lua'] = 'host_specific',
    ['tests/stress/test_stream_reactor_stress.lua'] = 'host_specific',
  },
}
