-- Luau build profiles and test capabilities.
return {
  entries = {
    'fibers',
    'fibers.channel',
    'fibers.diagnostics.io',
    'fibers.diagnostics.search',
    'fibers.effect',
    'fibers.host',
    'fibers.host.external',
    'fibers.host.manual',
    'fibers.host.pure',
    'fibers.host.roblox',
    'fibers.host.readiness',
    'fibers.mailbox',
    'fibers.roblox',
    'fibers.roblox.subscription',
    'fibers.op',
    'fibers.perform',
    'fibers.policy',
    'fibers.pulse',
    'fibers.region',
    'fibers.region.adoption',
    'fibers.region.settlement',
    'fibers.resource.authoring',
    'fibers.resource.clock',
    'fibers.resource.completion',
    'fibers.resource.counter',
    'fibers.resource.event_queue',
    'fibers.resource.flow',
    'fibers.resource.flow.errors',
    'fibers.resource.flow.rope',
    'fibers.resource.index',
    'fibers.resource.keyed',
    'fibers.resource.lease',
    'fibers.resource.queue',
    'fibers.resource.rendezvous',
    'fibers.resource.scalar',
    'fibers.resource.signal',
    'fibers.runtime',
    'fibers.scope',
    'fibers.sleep',
    'fibers.stream',
    'fibers.task',
  },
  profiles = {
    portable = {
      machine = 'ledger',
      module_entries = {
        'fibers.internal.reference_machine',
      },
      tests = {
        'tests/public/test_contracts.lua',
        'examples/test_documented_examples.lua',
        'tests/public/test_flow.lua',
        'tests/public/test_op.lua',
        'tests/public/test_policy.lua',
        'tests/public/test_performing_conveniences.lua',
        'tests/public/test_public_surface.lua',
        'tests/public/test_sleep.lua',
        'tests/public/test_stream_memory.lua',
        'examples/recipes/tests/test_messaging_and_countdown.lua',
        'examples/recipes/tests/test_priority_queue_composition.lua',
        'examples/recipes/tests/test_resources_and_pool.lua',
        'examples/recipes/tests/test_scalar_and_rate_limiter.lua',
        'tests/resources/test_counter_and_fifo.lua',
        'tests/resources/test_event.lua',
        'tests/resources/test_external_resources.lua',
        'tests/resources/test_index.lua',
        'tests/resources/test_index_lease_extended.lua',
        'tests/resources/test_lease_laws.lua',
        'tests/resources/test_scalar.lua',
        'tests/resources/test_state_resource_laws.lua',
        'tests/lifetimes/test_concurrent_task_settlement.lua',
        'tests/lifetimes/test_effects.lua',
        'tests/lifetimes/test_mixed_claim_exchange.lua',
        'tests/lifetimes/test_region_general.lua',
        'tests/lifetimes/test_region_laws.lua',
        'tests/lifetimes/test_region_lifecycle.lua',
        'tests/lifetimes/test_region_task_effects.lua',
        'tests/lifetimes/test_scope.lua',
        'tests/lifetimes/test_scope_authority_borrow.lua',
        'tests/lifetimes/test_scope_hardening.lua',
        'tests/lifetimes/test_scope_laws.lua',
        'tests/lifetimes/test_scope_policy_mechanisms.lua',
        'tests/lifetimes/test_scope_result_run.lua',
        'tests/lifetimes/test_scope_structural.lua',
        'tests/lifetimes/test_settlement_structure.lua',
        'tests/lifetimes/test_structured_policy.lua',
        'tests/embedding/test_host.lua',
        'tests/embedding/test_roblox.lua',
        'tests/embedding/test_host_handle.lua',
        'tests/embedding/test_readiness.lua',
        'tests/embedding/test_runtime.lua',
        'tests/embedding/test_runtime_lifecycle.lua',
        'tests/embedding/test_stream_host_handle.lua',
        'tests/embedding/test_stream_reactor.lua',
        'tests/kernel/test_claim_closure.lua',
        'tests/kernel/test_defeat.lua',
        'tests/kernel/test_dependency_supply_direction.lua',
        'tests/kernel/test_exchange_choice_propagation.lua',
        'tests/kernel/test_guard_activations.lua',
        'tests/kernel/test_instrumentation.lua',
        'tests/kernel/test_invariants.lua',
        'tests/kernel/test_kernel_machine.lua',
        'tests/kernel/test_ledger_kernel.lua',
        'tests/kernel/test_minimal_lazy_path.lua',
        'tests/kernel/test_residual_or_else.lua',
        'tests/kernel/test_resumable_search.lua',
        'tests/kernel/test_retry_laws.lua',
        'tests/kernel/test_retry_semantics.lua',
        'tests/kernel/test_search_limits.lua',
        'tests/kernel/test_search_stack.lua',
        'tests/kernel/test_slim_retention.lua',
        'tests/kernel/test_store_algebra.lua',
        'tests/kernel/test_store_rollback.lua',
        'tests/kernel/test_trail_journal.lua',
        'tests/kernel/test_validation_paths.lua',
        'tests/kernel/test_witness_validation.lua',
        'tests/internal/test_adoption_completion.lua',
        'tests/internal/test_datagram_service.lua',
        'tests/internal/test_flow_helpers.lua',
        'tests/internal/test_flow_scalar_state_machine.lua',
        'tests/internal/test_flow_settlement.lua',
        'tests/internal/test_flow_storage.lua',
        'tests/internal/test_flow_stream_adversarial.lua',
        'tests/internal/test_flow_validation.lua',
        'tests/internal/test_io_audit.lua',
        'tests/internal/test_protected.lua',
        'examples/case_studies/calendar/test_calendar.lua',
        'examples/case_studies/calendar/test_calendar_completeness.lua',
        'examples/case_studies/petri/test_petri.lua',
        'tests/performance/test_performance_architecture.lua',
      },
    },
    reference = {
      machine = 'reference',
      extends = 'portable',
      exclude = {
        'tests/kernel/test_ledger_kernel.lua',
        'tests/kernel/test_search_stack.lua',
        'tests/kernel/test_slim_retention.lua',
        'tests/kernel/test_trail_journal.lua',
        'tests/performance/test_performance_architecture.lua',
      },
    },
  },
  classifications = {
    ['examples/case_studies/calendar/test_calendar.lua'] = 'portable',
    ['examples/case_studies/calendar/test_calendar_completeness.lua'] = 'portable',
    ['examples/case_studies/petri/test_petri.lua'] = 'portable',
    ['examples/recipes/tests/test_messaging_and_countdown.lua'] = 'portable',
    ['examples/recipes/tests/test_priority_queue_composition.lua'] = 'portable',
    ['examples/recipes/tests/test_resources_and_pool.lua'] = 'portable',
    ['examples/recipes/tests/test_scalar_and_rate_limiter.lua'] = 'portable',
    ['tests/embedding/hosts/test_cffi_linux.lua'] = 'host_specific',
    ['tests/embedding/hosts/test_fd_cffi.lua'] = 'host_specific',
    ['tests/embedding/hosts/test_fd_luajit.lua'] = 'host_specific',
    ['tests/embedding/hosts/test_fd_luaposix.lua'] = 'host_specific',
    ['tests/embedding/hosts/test_fd_nixio.lua'] = 'host_specific',
    ['tests/embedding/hosts/test_luajit_linux.lua'] = 'host_specific',
    ['tests/embedding/hosts/test_luaposix.lua'] = 'host_specific',
    ['tests/embedding/hosts/test_nixio.lua'] = 'host_specific',
    ['tests/embedding/hosts/test_pure.lua'] = 'host_specific',
    ['tests/embedding/test_datagram_optional_providers.lua'] = 'host_specific',
    ['tests/embedding/test_fd_nixio_wrap.lua'] = 'host_specific',
    ['tests/embedding/test_host.lua'] = 'portable',
    ['tests/embedding/test_roblox.lua'] = 'portable',
    ['tests/embedding/test_host_handle.lua'] = 'portable',
    ['tests/embedding/test_host_linux.lua'] = 'host_specific',
    ['tests/embedding/test_host_poller.lua'] = 'host_specific',
    ['tests/embedding/test_process_nixio_provider.lua'] = 'host_specific',
    ['tests/embedding/test_readiness.lua'] = 'portable',
    ['tests/embedding/test_runtime.lua'] = 'portable',
    ['tests/embedding/test_runtime_lifecycle.lua'] = 'portable',
    ['tests/embedding/test_socket_resolver_optional_providers.lua'] = 'host_specific',
    ['tests/embedding/test_stream_host_handle.lua'] = 'portable',
    ['tests/embedding/test_stream_reactor.lua'] = 'portable',
    ['tests/internal/test_adoption_completion.lua'] = 'portable',
    ['tests/internal/test_bitops.lua'] = 'stock_lua_loader',
    ['tests/internal/test_datagram_service.lua'] = 'portable',
    ['tests/internal/test_flow_helpers.lua'] = 'portable',
    ['tests/internal/test_flow_scalar_state_machine.lua'] = 'portable',
    ['tests/internal/test_flow_settlement.lua'] = 'portable',
    ['tests/internal/test_flow_storage.lua'] = 'portable',
    ['tests/internal/test_flow_stream_adversarial.lua'] = 'portable',
    ['tests/internal/test_flow_validation.lua'] = 'portable',
    ['tests/internal/test_io_audit.lua'] = 'portable',
    ['tests/internal/test_protected.lua'] = 'portable',
    ['tests/internal/test_reference_lazy.lua'] = 'stock_lua_loader',
    ['tests/io/test_datagram.lua'] = 'host_specific',
    ['tests/io/test_datagram_conformance.lua'] = 'host_specific',
    ['tests/io/test_file.lua'] = 'host_specific',
    ['tests/io/test_foundations.lua'] = 'host_specific',
    ['tests/io/test_pipe.lua'] = 'host_specific',
    ['tests/io/test_process.lua'] = 'host_specific',
    ['tests/io/test_resolver.lua'] = 'host_specific',
    ['tests/io/test_socket.lua'] = 'host_specific',
    ['tests/io/test_socket_conformance.lua'] = 'host_specific',
    ['tests/io/test_socket_failure_matrix.lua'] = 'host_specific',
    ['tests/io/test_socket_hardening.lua'] = 'host_specific',
    ['tests/io/test_socket_lifecycle.lua'] = 'host_specific',
    ['tests/io/test_socket_provider_matrix.lua'] = 'host_specific',
    ['tests/kernel/test_claim_closure.lua'] = 'portable',
    ['tests/kernel/test_defeat.lua'] = 'portable',
    ['tests/kernel/test_dependency_supply_direction.lua'] = 'portable',
    ['tests/kernel/test_exchange_choice_propagation.lua'] = 'portable',
    ['tests/kernel/test_guard_activations.lua'] = 'portable',
    ['tests/kernel/test_instrumentation.lua'] = 'portable',
    ['tests/kernel/test_invariants.lua'] = 'portable',
    ['tests/kernel/test_kernel_machine.lua'] = 'portable',
    ['tests/kernel/test_ledger_kernel.lua'] = 'portable',
    ['tests/kernel/test_minimal_lazy_path.lua'] = 'portable',
    ['tests/kernel/test_residual_or_else.lua'] = 'portable',
    ['tests/kernel/test_resumable_search.lua'] = 'portable',
    ['tests/kernel/test_retry_laws.lua'] = 'portable',
    ['tests/kernel/test_retry_semantics.lua'] = 'portable',
    ['tests/kernel/test_search_limits.lua'] = 'portable',
    ['tests/kernel/test_search_stack.lua'] = 'portable',
    ['tests/kernel/test_slim_retention.lua'] = 'portable',
    ['tests/kernel/test_store_algebra.lua'] = 'portable',
    ['tests/kernel/test_store_rollback.lua'] = 'portable',
    ['tests/kernel/test_trail_journal.lua'] = 'portable',
    ['tests/kernel/test_validation_paths.lua'] = 'portable',
    ['tests/kernel/test_witness_validation.lua'] = 'portable',
    ['tests/lifetimes/test_concurrent_task_settlement.lua'] = 'portable',
    ['tests/lifetimes/test_effects.lua'] = 'portable',
    ['tests/lifetimes/test_mixed_claim_exchange.lua'] = 'portable',
    ['tests/lifetimes/test_region_general.lua'] = 'portable',
    ['tests/lifetimes/test_region_laws.lua'] = 'portable',
    ['tests/lifetimes/test_region_lifecycle.lua'] = 'portable',
    ['tests/lifetimes/test_region_task_effects.lua'] = 'portable',
    ['tests/lifetimes/test_scope.lua'] = 'portable',
    ['tests/lifetimes/test_scope_authority_borrow.lua'] = 'portable',
    ['tests/lifetimes/test_scope_hardening.lua'] = 'portable',
    ['tests/lifetimes/test_scope_laws.lua'] = 'portable',
    ['tests/lifetimes/test_scope_policy_mechanisms.lua'] = 'portable',
    ['tests/lifetimes/test_scope_result_run.lua'] = 'portable',
    ['tests/lifetimes/test_scope_structural.lua'] = 'portable',
    ['tests/lifetimes/test_settlement_structure.lua'] = 'portable',
    ['tests/lifetimes/test_structured_policy.lua'] = 'portable',
    ['tests/native/test_datagram_native.lua'] = 'host_specific',
    ['tests/native/test_process_native.lua'] = 'host_specific',
    ['tests/performance/test_performance_architecture.lua'] = 'portable',
    ['tests/public/test_contracts.lua'] = 'portable',
    ['examples/test_documented_examples.lua'] = 'portable',
    ['tests/public/test_flow.lua'] = 'portable',
    ['tests/public/test_op.lua'] = 'portable',
    ['tests/public/test_performing_conveniences.lua'] = 'portable',
    ['tests/public/test_policy.lua'] = 'portable',
    ['tests/public/test_public_surface.lua'] = 'portable',
    ['tests/public/test_sleep.lua'] = 'portable',
    ['tests/public/test_stream_memory.lua'] = 'portable',
    ['tests/resources/test_counter_and_fifo.lua'] = 'portable',
    ['tests/resources/test_event.lua'] = 'portable',
    ['tests/resources/test_external_resources.lua'] = 'portable',
    ['tests/resources/test_index.lua'] = 'portable',
    ['tests/resources/test_index_lease_extended.lua'] = 'portable',
    ['tests/resources/test_lease_laws.lua'] = 'portable',
    ['tests/resources/test_scalar.lua'] = 'portable',
    ['tests/resources/test_state_resource_laws.lua'] = 'portable',
    ['tests/stress/test_datagram_churn.lua'] = 'host_specific',
    ['tests/stress/test_socket_churn.lua'] = 'host_specific',
    ['tests/stress/test_stream_reactor_stress.lua'] = 'host_specific',
  },
}
