package.path = table.concat({ './?.lua', './?/init.lua', './?/?.lua', package.path }, ';')

local Op = require('et.op')

return function()
  local a = Op.always('x')
  assert(a and a.tag == 'always', 'Op.always constructs inert syntax')
  assert(Op.never().tag == 'never', 'Op.never constructs inert syntax')
  assert(a:map(function(x) return x end).tag == 'map', 'Op.map constructs inert syntax')
  assert(a:and_then(function() return Op.always(true) end).tag == 'bind', 'Op.and_then constructs inert syntax')
  assert(Op.choice(Op.never(), a).tag == 'choice', 'Op.choice constructs inert syntax')
  local claim = Op.claim({}, 'access', { tag = 'get' })
  assert(claim.tag == 'claim' and claim.claim_kind == 'access', 'Op.claim is the primitive claim syntax')
  assert(Op.access({}, {}).tag == 'claim', 'Op.access is a claim constructor alias')
  assert(Op.open_claim({}, {}).claim_kind == 'open_claim', 'Op.open_claim is a claim constructor alias')
  assert(Op.await({}, {}).claim_kind == 'await', 'Op.await is a claim constructor alias')
  assert(Op.with_obligation('generic', function(ref) return Op.always(ref.id) end).tag == 'with_obligation', 'Op.with_obligation constructs linear obligation syntax')
  assert(Op.nack({ __et_obligation = true, id = 'o' }).tag == 'obligation_observe', 'Op.nack observes an obligation')
  assert(Op.tensor({ a }).tag == 'tensor', 'Op.tensor constructs inert syntax')
  assert(Op.all({ a }).tag == 'all', 'Op.all constructs inert syntax')
  local wrapped = a:wrap(function(x) return x end)
  assert(wrapped.tag == 'wrap' and require('et.op').is_boundary(wrapped), 'Op.wrap constructs a continuation boundary')
  local ok = pcall(function() return wrapped:and_then(function() return a end) end)
  assert(not ok, 'wrap boundary rejects transactional sequencing')
  print('op tests: ok')
end
