-- Exact public module allow-list for Fibers v1.
--
-- Modules absent from this list are implementation details even when they are
-- present in the source tree. Optional modules may require host dependencies
-- which are not available in every test environment.

return {
  portable = {
    'fibers',
    'fibers.channel',
    'fibers.closure',
    'fibers.effect',
    'fibers.embed.application',
    'fibers.embed.external',
    'fibers.embed.manual',
    'fibers.embed.pure',
    'fibers.embed.queue',
    'fibers.embed.wait_set',
    'fibers.file',
    'fibers.grant',
    'fibers.io.auto',
    'fibers.io.error',
    'fibers.io.facility',
    'fibers.io.handle',
    'fibers.io.offer',
    'fibers.io.platform',
    'fibers.io.posix',
    'fibers.io.process',
    'fibers.io.readiness',
    'fibers.io.stream',
    'fibers.latch',
    'fibers.lifetime',
    'fibers.mailbox',
    'fibers.net.address',
    'fibers.op',
    'fibers.process',
    'fibers.protected',
    'fibers.pulse',
    'fibers.resource.authoring',
    'fibers.resource.cell',
    'fibers.resource.clock',
    'fibers.resource.counter',
    'fibers.resource.event_queue',
    'fibers.resource.fifo',
    'fibers.resource.flow',
    'fibers.resource.index',
    'fibers.resource.keyed',
    'fibers.resource.lease',
    'fibers.resource.machine',
    'fibers.resource.ref_count',
    'fibers.resource.rendezvous',
    'fibers.resource.signal',
    'fibers.roblox',
    'fibers.roblox.host',
    'fibers.roblox.subscription',
    'fibers.runtime',
    'fibers.scope',
    'fibers.semaphore',
    'fibers.sleep',
    'fibers.socket',
    'fibers.stream',
    'fibers.task',
  },
  optional = {
    'fibers.io.cffi_linux',
    'fibers.io.ffi_linux',
    'fibers.io.luajit_linux',
    'fibers.io.luaposix',
    'fibers.io.nixio',
  },
}
