name: Continuous Integration

on: [pull_request]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jangala-dev/mini-lua-image:bookworm
      options: --user 0:0

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Run custom install script
      run: |
        chmod +x .devcontainer/postCreateCommand.sh
        ./.devcontainer/postCreateCommand.sh

    - name: Run lua 5.1 Tests in Tests Directory
      run: |
        cd tests
        lua test.lua

    - name: Run luajit 2.1 Tests in Tests Directory
      run: |
        cd tests
        luajit test.lua

    # - name: Run Linter
    #   run: luacheck .

